
import "./globals.css";
import NavBar from "./components/NavBar";
import { ReactNode } from "react";
import ProviderWrapper from "./components/ProviderWrapper";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Effive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ProviderWrapper>
          <Toaster position="top-right" />
          <div className="grid grid-cols-5 h-screen ">
            <NavBar className="col-span-1 h-full p-5 pt-4 border-r border-gray-300 flex flex-col gap-5" />
            <div className="col-span-4">{children}</div>
          </div>
        </ProviderWrapper>
      </body>
    </html>
  );
}
